# Generated by Django 5.1.3 on 2024-12-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_remove_vaga_status_vaga_veiculo_alter_veiculo_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='motorista',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vaga', to='monitoramento.motorista'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='veiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vaga', to='monitoramento.veiculo'),
        ),
    ]
