# Generated by Django 5.1.3 on 2024-12-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_vaga_motorista_alter_vaga_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
